#Data Source
spring:
  data:
    mongodb:
      username: etiennecassin
      password: Pa$$w0rd
      uri: mongodb+srv://etiennecassin:Pa$$w0rd@cluster-eni.qnoct.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-ENI
      port: 27017
      database: Demo_ENI_Ecole
      authentication-database: admin
      auto-index-creation: true

#Log
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
